// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI commands (migrate/generate/studio) use the DIRECT (non-pooled)
    // connection — advisory locks used by `migrate` don't work through Neon's
    // PgBouncer pooler. The runtime client (lib/db.ts) uses DATABASE_URL
    // (pooled) independently of this config.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
