import type { IconType } from "react-icons";
import {
  FaAws,
  FaDatabase,
  FaJava,
  FaLink,
  FaNetworkWired,
  FaRobot,
  FaServer,
  FaShieldAlt,
  FaSyncAlt,
} from "react-icons/fa";
import {
  SiAngular,
  SiC,
  SiCplusplus,
  SiCss,
  SiDjango,
  SiDocker,
  SiExpress,
  SiFlask,
  SiFlutter,
  SiGit,
  SiGo,
  SiGooglecloud,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiKotlin,
  SiKubernetes,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNetlify,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiPandas,
  SiPhp,
  SiPostgresql,
  SiPython,
  SiPytorch,
  SiReact,
  SiRedis,
  SiRuby,
  SiRubyonrails,
  SiRust,
  SiScikitlearn,
  SiSharp,
  SiSpringboot,
  SiSqlite,
  SiSvelte,
  SiSwift,
  SiTensorflow,
  SiTerraform,
  SiTypescript,
  SiVercel,
  SiVuedotjs,
} from "react-icons/si";
import { VscAzure } from "react-icons/vsc";

export interface TechItem {
  name: string;
  Icon: IconType;
}

// Technical languages/tools only (from project_stack's PREDEFINED_SKILLS +
// skillIconMap) — no soft skills / business / creative.
export const TECH_STACK: TechItem[] = [
  { name: "Python", Icon: SiPython },
  { name: "C", Icon: SiC },
  { name: "C++", Icon: SiCplusplus },
  { name: "Java", Icon: FaJava },
  { name: "JavaScript", Icon: SiJavascript },
  { name: "TypeScript", Icon: SiTypescript },
  { name: "HTML", Icon: SiHtml5 },
  { name: "CSS", Icon: SiCss },
  { name: "React", Icon: SiReact },
  { name: "Next.js", Icon: SiNextdotjs },
  { name: "Vue", Icon: SiVuedotjs },
  { name: "Angular", Icon: SiAngular },
  { name: "Svelte", Icon: SiSvelte },
  { name: "Node.js", Icon: SiNodedotjs },
  { name: "Django", Icon: SiDjango },
  { name: "Flask", Icon: SiFlask },
  { name: "Ruby on Rails", Icon: SiRubyonrails },
  { name: "Express.js", Icon: SiExpress },
  { name: "Spring Boot", Icon: SiSpringboot },
  { name: "SQL", Icon: FaDatabase },
  { name: "PostgreSQL", Icon: SiPostgresql },
  { name: "MongoDB", Icon: SiMongodb },
  { name: "MySQL", Icon: SiMysql },
  { name: "SQLite", Icon: SiSqlite },
  { name: "Redis", Icon: SiRedis },
  { name: "AWS", Icon: FaAws },
  { name: "Azure", Icon: VscAzure },
  { name: "Google Cloud", Icon: SiGooglecloud },
  { name: "Vercel", Icon: SiVercel },
  { name: "Netlify", Icon: SiNetlify },
  { name: "Docker", Icon: SiDocker },
  { name: "Kubernetes", Icon: SiKubernetes },
  { name: "Git", Icon: SiGit },
  { name: "Linux", Icon: SiLinux },
  { name: "CI/CD", Icon: FaSyncAlt },
  { name: "Terraform", Icon: SiTerraform },
  { name: "TensorFlow", Icon: SiTensorflow },
  { name: "PyTorch", Icon: SiPytorch },
  { name: "Scikit-learn", Icon: SiScikitlearn },
  { name: "Machine Learning", Icon: FaRobot },
  { name: "Pandas", Icon: SiPandas },
  { name: "NumPy", Icon: SiNumpy },
  { name: "GraphQL", Icon: SiGraphql },
  { name: "REST API", Icon: FaNetworkWired },
  { name: "gRPC", Icon: FaServer },
  { name: "Go", Icon: SiGo },
  { name: "Rust", Icon: SiRust },
  { name: "Kotlin", Icon: SiKotlin },
  { name: "Swift", Icon: SiSwift },
  { name: "PHP", Icon: SiPhp },
  { name: "Ruby", Icon: SiRuby },
  { name: "C#", Icon: SiSharp },
  { name: "React Native", Icon: SiReact },
  { name: "Flutter", Icon: SiFlutter },
  { name: "Cybersecurity", Icon: FaShieldAlt },
  { name: "Blockchain", Icon: FaLink },
];

export const TECH_BY_NAME: Record<string, TechItem> = Object.fromEntries(
  TECH_STACK.map((t) => [t.name, t]),
);
